name: BedrockOffhand
version: ${version}
main: com.noty215.hand.BedrockOffhandPlugin
api-version: '1.21'
description: Offhand support for Bedrock players on Java servers
author: noty215
website: https://github.com/noty215

# Use softdepend instead of depend to make it optional
softdepend: [Geyser-Spigot, floodgate]

commands:
  offhand:
    description: Manage your offhand items
    usage: /<command> [info|clear|set]
    permission: bedrockoffhand.use

permissions:
  bedrockoffhand.use:
    description: Allows players to use offhand commands
    default: true